# Generated by Django 2.0.5 on 2018-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='frontmatter',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
